### ISSUE TITLE
unable to clone jimmdd/node-oracle-layers-serverless's contents

### ISSUE THREAD

**Issue by hosamshahin** [jimmdd/node-oracle-layers-serverless#4]
We're sorry, something went wrong.
We were unable to clone jimmdd/node-oracle-layers-serverless's contents into hosamshahin/node-oracle-layers-serverless. The template you used includes files that are larger than 10 megabytes. Please ask jimmdd to remove those files from the template and try again.

**Comment by jimmdd** [comment]
Hi, I wasn't aware that GitHub has this size limit on template. Please clone or download it directly.  it's required to have the compiled oracle driver in the repo which is the large files that cause the issue. I'll remove the template option on this repo. Thanks for reporting the problem.
